volumes:
  postgres_volume:

services:
  app:
    image: test-app:v1
    build:
      context: .
      dockerfile: src/Dockerfile
    expose:
      - "8080"
    restart: always
    depends_on:
      - postgres
    deploy:
      replicas: 5
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app
    restart: always

  postgres:
    image: postgres:15-alpine3.17
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  migrator:
    build:
      context: .
      dockerfile: pkg/postgres/migrator.Dockerfile
    depends_on:
      - postgres
    restart: on-failure
    environment:
      DB_HOST: postgres